services:
  - type: web
    name: nirabhi-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python main.py"
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false

  - type: web
    name: nirabhi-frontend
    env: node
    buildCommand: "cd frontend && npm install --legacy-peer-deps && npm run build"
    startCommand: "cd frontend && npx serve -s build -p 10000"
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        value: https://nirabhi-backend.onrender.com
